server:
  port: 1991

spring:
  datasource:
    url: ${DB_URL}
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_SENDER}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true

    url: ${BASE_URL}
    sender: ${MAIL_SENDER}
    confirm-email:
      subject: ${CONFIRM_EMAIL_SUBJECT}
      content: ${CONFIRM_EMAIL_CONTENT}
    forgot-pass:
      subject: ${FORGOT_PASS_SUBJECT}
      content: ${FORGOT_PASS_CONTENT}

  config:
    import: env.properties
    jwt:
      secret: ${SECRET_KEY}

  sql:
    init:
      mode: always
      schema-locations: classpath:/sql/schema.sql
      data-locations:  classpath:/sql/data.sql

logging:
  level:
    root: INFO
